openapi: 3.1.0
info:
  title: API сервер для демо-проекта «fit-friends».
  description: |-
    * Список ресурсов и маршрутов сервера «fit-friends».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: notifications
    description: Действия с уведомлениями.
  - name: orders
    description: Действия с заказами.
  - name: personal-trainings
    description: Действия с персональными тренировками.
  - name: reviews
    description: Действия с отзывами.
  - name: trainings
    description: Действия с тренировками.
  - name: users
    description: Действия с пользователями.
  - name: user-balances
    description: Действия с балансами пользователя.

paths:
  /notifications/create:
    post:
      tags:
        - notifications
      summary: Создание уведомления.
      description: Создание уведомления.

  /notifications/{userId}:
    get:
      tags:
        - notifications
      summary: Просмотр уведомления.
      description: Просмотр уведомления по идентификатору.

  /notifications/{notificationId}:
    delete:
      tags:
        - notifications
      summary: Удаление уведомления.
      description: Удаление уведомления по идентификатору.

  /orders:
    get:
      tags:
        - orders
      summary: Просмотр списка заказов.
      description: Просмотр списка заказов.

  /orders/{orderId}:
    get:
      tags:
        - orders
      summary: Просмотр заказа.
      description: Просмотр заказа по идентификатору.

  /orders/create:
    post:
      tags:
        - orders
      summary: Создание заказа.
      description: Создание заказа.

  /personal-trainings:
    get:
      tags:
        - personal-trainings
      summary: Просмотр списка персональных тренировок.
      description: Просмотр списка персональных тренировок.

  /personal-trainings/create:
    post:
      tags:
        - personal-trainings
      summary: Создание персональной тренировки.
      description: Создание персональной тренировки.

  /personal-trainings/{personalTrainingId}:
    get:
      tags:
        - personal-trainings
      summary: Редактирование персональной тренировки.
      description: Редактирование персональной тренировки по идентификатору.

  /reviews:
    get:
      tags:
        - reviews
      summary: Просмотр списка отзывов.
      description: Просмотр списка отзывов.

  /reviews/create:
    post:
      tags:
        - reviews
      summary: Создание отзыва.
      description: Создание отзыва.

  /trainings/create:
    post:
      tags:
        - trainings
      summary: Создание тренировки.
      description: Создание тренировки.

  /trainings/{userId}:
    get:
      tags:
        - trainings
      summary: Просмотр списка тренировок пользователя .
      description: Просмотр списка тренировок пользователя по идентификатору.

  /trainings/{trainerId}:
    get:
      tags:
        - trainings
      summary: Просмотр списка тренировок тренера .
      description: Просмотр списка тренировок тренера по идентификатору.

  /trainings:
    get:
      tags:
        - trainings
      summary: Просмотр списка тренировок.
      description: Просмотр списка тренировок.

  /trainings/{trainingId}:
    put:
      tags:
        - trainings
      summary: Редактирование тренировки.
      description: Редактирование тренировки по идентификатору.

  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля

  /users/info/{userId}:
    get:
      tags:
        - users
      summary: Просмотр пользователя
      description: Просмотр пользователя по идентификатору.

  /users/{userId}:
    put:
      tags:
        - users
      summary: Редактирование пользователя
      description: Редактирование пользователя по идентификатору.

  /users:
    get:
      tags:
        - users
      summary: Просмотр списка пользователей
      description: Просмотр списка пользователей

  /user-balances/get/{userId}:
    get:
      tags:
        - user-balances
      summary: Просмотр баланса пользователя
      description: Просмотр баланса пользователя по идентификатору.

  /user-balances/{userId}:
    put:
      tags:
        - user-balances
      summary: Редактирование баланса пользователя
      description: Редактирование баланса пользователя по идентификатору.
  




