GET http://localhost:5000/user-balance/aas123415asxd HTTP/1.1
Content-Type: application/json

###

POST http://localhost:5000/user-balances HTTP/1.1
Content-Type: application/json

{
  "userId": "aas123415asxd",
  "training": "6620100b5fdea4a2c5fbaf98",
  "quantityTraining": 10
}

###

PUT http://localhost:5000/user-balances/66200cac04dee381d9d01b2a HTTP/1.1
Content-Type: application/json

{
  "quantityTraining": 50
}