## Получения количества тренировок пользователя
GET http://localhost:5000/user-balances/661ffa52db68976f5f55c689 HTTP/1.1
Content-Type: application/json

###
## Создание баланаса пользователя
POST http://localhost:5000/user-balances HTTP/1.1
Content-Type: application/json

{
  "userId": "aas123415asxd",
  "training": "6620100b5fdea4a2c5fbaf98",
  "quantityTraining": 10
}

###

## Обновления баланса пользователя
PUT http://localhost:5000/user-balances/66200cac04dee381d9d01b2a HTTP/1.1
Content-Type: application/json

{
  "quantityTraining": 20
}