export type MockUserDate = {
  names: string[]
  emails: string[]
  avatars: string[]
  passwords: string[]
  genders: string[]
  birthdays: string[]
  roles: string[]
  descriptions: string[]
  locations: string[]
  images: string[]
  createdAt: string[]
  trainingLevels: string[]
  trainingTypes: string[]
  trainingDurations: string[]
  caloriesPerDay: string[]
  caloriesPerWorkout:string[]
  isAvailableForTraining: string[]
  certificates: string[]
  achievements: string[]
  privateTraining: string[]

}