#Trainings
##Get all trainings 

POST  http://localhost:5000/trainings HTTP/1.1
Content-Type: application/json

{
  "title": "this is tytle",
  "backgroundImage": "this is tytle",
  "level": "beginner",
  "trainingType": "йога",
  "duration": "10-30 min",
  "price": 1200,
  "calories": 1200,
  "description": "this training for realy fat guys",
  "gender": "female",
  "video": "female",
  "rating": 4,
  "trainerId": "661ffa52db68976f5f55c68e",
  "specialOffer": false
}

###
