export const Component = {
  RestApplication: Symbol.for('RestApplication'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  UserService: Symbol.for('UserService'),
  UserModel: Symbol.for('UserModel'),
  UserBalanceModel: Symbol.for('UserBalanceModel'),
  UserBalanceService: Symbol.for('UserBalanceService'),
  NotificationService: Symbol.for('NotificationService'),
  NotificationModel: Symbol.for('NotificationModel'),
  OrderService: Symbol.for('OrderService'),
  OrderModel: Symbol.for('OrderModel'),
  PersonalTrainingService: Symbol.for('PersonalTrainingService'),
  PersonalTrainingModel: Symbol.for('PersonalTrainingModel'),
  ReviewService: Symbol.for('ReviewService'),
  ReviewModel: Symbol.for('ReviewModel'),
  TrainingService: Symbol.for('TrainingService'),
  TrainingModel: Symbol.for('TrainingModel'),
  UserBalanceController: Symbol.for('UserBalanceController'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  UserController: Symbol.for('UserController'),
  TrainingController: Symbol.for('TrainingController'),
  ReviewController: Symbol.for('ReviewController'),
} as const;     